// swift-tools-version: 5.9
// Generated by `flutter-tvos plugin port`. Do not edit by hand.
//
// This manifest lets the package be consumed via Swift Package Manager. The
// target reuses the same `Classes/` sources the CocoaPods podspec compiles, so
// both dependency managers stay in sync from a single source tree.
import PackageDescription

let package = Package(
  name: "games_services_tvos",
  platforms: [
    .tvOS(.v15),
  ],
  products: [
    .library(name: "games-services-tvos", targets: ["games_services_tvos"]),
  ],
  dependencies: [
    // Lets the target `import Flutter`. flutter-tvos generates the (empty)
    // FlutterFramework package as a sibling of this one under the app's
    // ephemeral SwiftPM packages, so `../FlutterFramework` resolves at build
    // time, and stages Flutter.framework into BUILT_PRODUCTS_DIR, where the
    // compiler finds it. Matches stock Flutter's plugin Package.swift.
    .package(name: "FlutterFramework", path: "../FlutterFramework"),
  ],
  targets: [
    .target(
      name: "games_services_tvos",
      dependencies: [
        .product(name: "FlutterFramework", package: "FlutterFramework"),
      ],
      path: "Classes",
      swiftSettings: [
        // Keep Swift `#if TARGET_OS_TV` branches active, matching the podspec.
        .define("TARGET_OS_TV"),
      ]
    ),
  ]
)
